./../bench/ddr3_tb/ddr_test_top_tb.v
./../bench/mem/ddr3.v
./../bench/mem/ddr3_parameters.vh
./../src/ddr3_test_top.v
./../src/ddr3_wr_ctrl.v
./../src/ddr3_rd_ctrl.v
./../src/user_data_gen.v
./../src/user_data_recv.v
./../src/wr_driver.v
./../src/rd_driver.v
./../src/ipsxb_rst_sync.v
./../src/key_filter.v
./../pnr/ipcore/async_fifo_8to256/rtl/ipml_fifo_ctrl_v1_3.v
./../pnr/ipcore/async_fifo_8to256/rtl/ipml_fifo_v1_6_async_fifo_8to256.v
./../pnr/ipcore/async_fifo_8to256/rtl/ipml_sdpram_v1_6_async_fifo_8to256.v
./../pnr/ipcore/async_fifo_8to256/async_fifo_8to256.v
// ./../pnr/ipcore/async_fifo_256to8_ext/rtl/ipml_fifo_ctrl_v1_3.v
./../pnr/ipcore/async_fifo_256to8_ext/rtl/ipml_fifo_v1_6_async_fifo_256to8_ext.v
./../pnr/ipcore/async_fifo_256to8_ext/rtl/ipml_sdpram_v1_6_async_fifo_256to8_ext.v
./../pnr/ipcore/async_fifo_256to8_ext/async_fifo_256to8_ext.v


./../pnr/ipcore/ddr3_test/rtl/ipsxb_rst_sync_v1_1.v
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_calib_mux_v1_3.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_calib_top_v1_3.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_control_path_adj_v1_0.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_data_slice_v1_4.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_data_slice_dqs_gate_cal_v1_3.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_data_slice_wrlvl_v1_4.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_dfi_v1_4.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_dll_update_ctrl_v1_0.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_dqsi_rdel_cal_v1_2.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_dqs_gate_coarse_cal_v1_3.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_dqs_rddata_align_v1_3.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_drift_ctrl_v1_3.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_gate_update_ctrl_v1_3.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_gatecal_v1_3.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_info_v1_0.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_init_v1_0.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_main_ctrl_v1_3.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_rdcal_v1_2.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_reset_ctrl_v1_4.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_rst_debounce_v1_0.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_slice_rddata_align_v1_0.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_training_ctrl_v1_0.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_upcal_v1_4.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_wdata_path_adj_v1_0.vp
./../sim_lib/rtl/ddrphy/ipsxb_ddrphy_wrlvl_v1_0.vp
./../pnr/ipcore/ddr3_test/rtl/ddrphy/ipsxb_ddrphy_slice_top_v1_4.v
./../pnr/ipcore/ddr3_test/rtl/pll/ipsxb_ddrphy_pll_v1_0.v
./../sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_apb_cross_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_calib_delay_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_cfg_apb_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_dcd_bm_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_dcd_rowaddr_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_dcd_sm_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_dcd_top_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_dcp_back_ctrl_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_dcp_buf_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_dcp_out_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_dcp_top_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_dfi_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_lp_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_mrs_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_prefetch_fifo_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_rdatapath_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_reg_fifo2_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_ui_axi_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_wdatapath_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_wdp_align_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_wdp_dcp_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_wrapper_v1_2a.vp
./../sim_lib/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_com_timing_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_tfaw_timing_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_tfaw_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_act2wr_pass_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_act_pass_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_pre_pass_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_rd_pass_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_ref_pass_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_wr_pass_v1_2.vp
./../sim_lib/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_trc_timing_v1_2.vp
./../pnr/ipcore/ddr3_test/rtl/mcdq_ctrl/distributed_fifo/ipsxb_distributed_fifo_v1_0.v
./../pnr/ipcore/ddr3_test/rtl/mcdq_ctrl/distributed_fifo/rtl/ipsxb_distributed_fifo_ctr_v1_0.v
./../pnr/ipcore/ddr3_test/rtl/mcdq_ctrl/distributed_fifo/rtl/ipsxb_distributed_fifo_v1_0_distributed_fifo_v1_0.v
./../pnr/ipcore/ddr3_test/rtl/mcdq_ctrl/distributed_fifo/rtl/ipsxb_distributed_sdpram_v1_0_distributed_fifo_v1_0.v
D:/Tools/pango/PDS_2022.1/ip/system_ip/ipsxb_hmic_s/ipsxb_hmic_eval/ipsxb_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/GTP_DLL.v
D:/Tools/pango/PDS_2022.1/ip/system_ip/ipsxb_hmic_s/ipsxb_hmic_eval/ipsxb_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/GTP_DDC_E1.v
D:/Tools/pango/PDS_2022.1/ip/system_ip/ipsxb_hmic_s/ipsxb_hmic_eval/ipsxb_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/GTP_OSERDES.v
D:/Tools/pango/PDS_2022.1/ip/system_ip/ipsxb_hmic_s/ipsxb_hmic_eval/ipsxb_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/GTP_OUTBUFT.v
D:/Tools/pango/PDS_2022.1/ip/system_ip/ipsxb_hmic_s/ipsxb_hmic_eval/ipsxb_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/GTP_OUTBUFTCO.v
D:/Tools/pango/PDS_2022.1/ip/system_ip/ipsxb_hmic_s/ipsxb_hmic_eval/ipsxb_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/GTP_GRS.v
D:/Tools/pango/PDS_2022.1/ip/system_ip/ipsxb_hmic_s/ipsxb_hmic_eval/ipsxb_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/GTP_CLKBUFG.v
D:/Tools/pango/PDS_2022.1/ip/system_ip/ipsxb_hmic_s/ipsxb_hmic_eval/ipsxb_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/GTP_PLL_E3.v
D:/Tools/pango/PDS_2022.1/ip/system_ip/ipsxb_hmic_s/ipsxb_hmic_eval/ipsxb_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/GTP_IOCLKBUF.v
D:/Tools/pango/PDS_2022.1/ip/system_ip/ipsxb_hmic_s/ipsxb_hmic_eval/ipsxb_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/GTP_IOCLKDIV.v
D:/Tools/pango/PDS_2022.1/ip/system_ip/ipsxb_hmic_s/ipsxb_hmic_eval/ipsxb_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/GTP_IOBUFCO.v
D:/Tools/pango/PDS_2022.1/ip/system_ip/ipsxb_hmic_s/ipsxb_hmic_eval/ipsxb_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/GTP_IOBUF.v
D:/Tools/pango/PDS_2022.1/ip/system_ip/ipsxb_hmic_s/ipsxb_hmic_eval/ipsxb_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/GTP_IODELAY.v
D:/Tools/pango/PDS_2022.1/ip/system_ip/ipsxb_hmic_s/ipsxb_hmic_eval/ipsxb_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/GTP_ISERDES.v
./../pnr/ipcore/ddr3_test/ddr3_test.v
./../pnr/ipcore/ddr3_test/ddr3_test_ddrphy_top.v
 
+define+SIMULATION  
+define+den4096Mb   
+define+sg25E       
+define+x16         
