#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Thu Feb 23 21:42:52 2023

set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module test_ddr
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module test_ddr
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream 
